name: Testing Using Jest

on:
  push:
    branches:
      - main # Adjust branch name as needed
  pull_request:
    branches:
      - main # Adjust branch name as needed

jobs:
  test:
    name: Unit Test
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test
